<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyKhachSan" Class="DatabaseQLKSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-TAH3T3C\SQLEXPRESS;Initial Catalog=QuanLyKhachSan;Persist Security Info=True;User ID=sa" SettingsObjectName="BaiTapLon.Properties.Settings" SettingsPropertyName="QuanLyKhachSanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietHoaDon" Member="ChiTietHoaDons">
    <Type Name="ChiTietHoaDon">
      <Column Name="ChiTietHoaDonId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoaDonId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DichVuId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaDv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DichVu_ChiTietHoaDon" Member="DichVu" ThisKey="DichVuId" OtherKey="DichVuId" Type="DichVu" IsForeignKey="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="HoaDon" ThisKey="HoaDonId" OtherKey="HoaDonId" Type="HoaDon" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="DichVuId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaDv" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DichVu_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="DichVuId" OtherKey="DichVuId" Type="ChiTietHoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="HoaDonId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NhanVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KhachHangId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhongId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenLoai" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoDem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoKhach" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayHD" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TongTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HoaDon_ChiTietHoaDon" Member="ChiTietHoaDons" ThisKey="HoaDonId" OtherKey="HoaDonId" Type="ChiTietHoaDon" />
      <Association Name="KhachHang_HoaDon" Member="KhachHang" ThisKey="KhachHangId" OtherKey="KhachHangId" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="NhanVienId" OtherKey="NhanVienId" Type="NhanVien" IsForeignKey="true" />
      <Association Name="Phong_HoaDon" Member="Phong" ThisKey="PhongId" OtherKey="PhongId" Type="Phong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="KhachHangId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QuocTich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KhachHang_HoaDon" Member="HoaDons" ThisKey="KhachHangId" OtherKey="KhachHangId" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.LichLamViec" Member="LichLamViecs">
    <Type Name="LichLamViec">
      <Column Name="LichLamViecId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NhanVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ca" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Ngay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_LichLamViec" Member="NhanVien" ThisKey="NhanVienId" OtherKey="NhanVienId" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="LoaiPhongId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="LoaiPhongId" OtherKey="LoaiPhongId" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="NhanVienId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="NhanVienId" OtherKey="NhanVienId" Type="HoaDon" />
      <Association Name="NhanVien_LichLamViec" Member="LichLamViecs" ThisKey="NhanVienId" OtherKey="NhanVienId" Type="LichLamViec" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="PhongId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LoaiPhongId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaPhong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Phong_HoaDon" Member="HoaDons" ThisKey="PhongId" OtherKey="PhongId" Type="HoaDon" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="LoaiPhongId" OtherKey="LoaiPhongId" Type="LoaiPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VatTu" Member="VatTus">
    <Type Name="VatTu">
      <Column Name="VatTuId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenVatTu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>